export const ROUTES = {
  HOME: '/',
  AUTH: {
    LOGIN: '/entrar',
    FORGOT_PASSWORD: '/esqueci-minha-senha',
    RESET_PASSWORD: '/redefinir-senha',
  },
  SETTINGS: {
    HOME: '/configuracoes',
    CHANGE_PASSWORD: '/configuracoes/alterar-senha',
    USERS: '/configuracoes/usuarios',
    NEW_USER: '/configuracoes/usuarios/novo',
    RESET_USER_PASSWORD: (id: string) => `/configuracoes/usuarios/${id}/redefinir-senha`,
    EDIT_USER_ROLE: (id: string) => `/configuracoes/usuarios/${id}/papel`,
    DEVICES: '/configuracoes/dispositivos',
    SEND_PUSH: '/configuracoes/dispositivos/enviar-notificacao',
  },
  COMMUNITIES: {
    HOME: '/',
    ADD: '/adicionar-comunidade',
    DETAILS: (slug: string) => `/${slug}`,
    EDIT: (slug: string) => `/${slug}/editar`,
    ABOUT: (slug: string) => `/${slug}/sobre`,
    PATRON: (slug: string) => `/${slug}/padroeiro`,
    GALLERY: (slug: string) => `/${slug}/galeria`,
    MASS_SCHEDULES: {
      ADD_ORDINARY: (slug: string) => `/${slug}/adicionar-missa-regular`,
      EDIT_ORDINARY: (slug: string, id: string) => `/${slug}/missa-regular/${id}/editar`,
      ADD_DEVOTIONAL: (slug: string) => `/${slug}/adicionar-missa-devocional`,
      EDIT_DEVOTIONAL: (slug: string, id: string) => `/${slug}/missa-devocional/${id}/editar`,
      ADD_ANNUAL: (slug: string) => `/${slug}/adicionar-missa-anual`,
      EDIT_ANNUAL: (slug: string, id: string) => `/${slug}/missa-anual/${id}/editar`,
    },
  },
  CLERGY: {
    HOME: '/clerigos',
    ADD: '/clerigos/adicionar',
    EDIT: (id: string) => `/clerigos/editar/${id}`,
  },
  ANNOUNCEMENTS: {
    HOME: '/avisos',
    ADD: '/avisos/adicionar',
    EDIT: (id: string) => `/avisos/editar/${id}`,
    EDIT_ALERT: '/avisos/alerta/editar',
  },
  CALENDAR: {
    HOME: '/agenda',
    ADD_EVENT: '/agenda/adicionar-evento',
    ADD_EVENT_WITH_DATE: (date: string) => `/agenda/adicionar-evento?date=${date}`,
    EDIT_EVENT: (id: string) => `/agenda/evento/${id}/editar`,
  },
  SECRETARIAT: {
    HOME: '/secretaria',
    EDIT: '/secretaria/editar',
    DONATIONS: '/secretaria/doacoes',
  },
  PASTORALS: '/pastorais',
  APPOINTMENTS: {
    HOME: '/agendamentos',
    LIST: '/agendamentos/solicitacoes',
    ADD: '/agendamentos/adicionar',
    EDIT: (id: string) => `/agendamentos/editar/${id}`,
    REPORT: '/agendamentos/relatorio',
    DETAILS: (id: string) => `/agendamentos/${id}`,
  },
  PASTORAL_AGENTS: {
    HOME: '/agendamentos/agentes-pastorais',
    ADD: '/agendamentos/agentes-pastorais/adicionar',
    EDIT: (id: string) => `/agendamentos/agentes-pastorais/editar/${id}`,
    SCHEDULE: (id: string) => `/agendamentos/agentes-pastorais/${id}/horarios`,
    BLOCKED_DATES: (id: string) => `/agendamentos/agentes-pastorais/${id}/bloqueios`,
  },
  APPOINTMENT_SERVICES: {
    HOME: '/agendamentos/categorias-atendimento',
    ADD: '/agendamentos/categorias-atendimento/adicionar',
    EDIT: (id: string) => `/agendamentos/categorias-atendimento/editar/${id}`,
  },
  HELP: {
    HOME: '/ajuda',
    APPOINTMENTS: '/ajuda/agendamentos',
    SECRETARIAT: '/ajuda/secretaria',
    COMMUNITIES: '/ajuda/comunidades',
    CLERGY: '/ajuda/clerigos',
    ANNOUNCEMENTS: '/ajuda/avisos',
    USERS: '/ajuda/usuarios',
    FIRST_STEPS: '/ajuda/primeiros-passos',
    FAQ: '/ajuda/faq',
  },
} as const;

