export const ROUTES = {
  HOME: '/dados-institucionais',
  AUTH: {
    LOGIN: '/entrar',
    FORGOT_PASSWORD: '/esqueci-minha-senha',
    RESET_PASSWORD: '/redefinir-senha',
  },
  SETTINGS: {
    HOME: '/configuracoes',
    CHANGE_PASSWORD: '/configuracoes/alterar-senha',
    USERS: '/configuracoes/usuarios',
    NEW_USER: '/configuracoes/usuarios/novo',
    RESET_USER_PASSWORD: (id: string) => `/configuracoes/usuarios/${id}/redefinir-senha`,
    EDIT_USER_ROLE: (id: string) => `/configuracoes/usuarios/${id}/papel`,
    DEVICES: '/configuracoes/dispositivos',
    SEND_PUSH: '/configuracoes/dispositivos/enviar-notificacao',
  },
  COMMUNITIES: {
    HOME: '/dados-institucionais',
    ADD: '/dados-institucionais/adicionar-comunidade',
    DETAILS: (slug: string) => `/dados-institucionais/${slug}`,
    EDIT: (slug: string) => `/dados-institucionais/${slug}/editar`,
    ABOUT: (slug: string) => `/dados-institucionais/${slug}/sobre`,
    PATRON: (slug: string) => `/dados-institucionais/${slug}/padroeiro`,
    GALLERY: (slug: string) => `/dados-institucionais/${slug}/galeria`,
    MASS_SCHEDULES: {
      ADD_ORDINARY: (slug: string) => `/dados-institucionais/${slug}/adicionar-missa-regular`,
      EDIT_ORDINARY: (slug: string, id: string) => `/dados-institucionais/${slug}/missa-regular/${id}/editar`,
      ADD_DEVOTIONAL: (slug: string) => `/dados-institucionais/${slug}/adicionar-missa-devocional`,
      EDIT_DEVOTIONAL: (slug: string, id: string) => `/dados-institucionais/${slug}/missa-devocional/${id}/editar`,
      ADD_ANNUAL: (slug: string) => `/dados-institucionais/${slug}/adicionar-missa-anual`,
      EDIT_ANNUAL: (slug: string, id: string) => `/dados-institucionais/${slug}/missa-anual/${id}/editar`,
    },
  },
  CLERGY: {
    HOME: '/dados-institucionais/clerigos',
    ADD: '/dados-institucionais/clerigos/adicionar',
    EDIT: (id: string) => `/dados-institucionais/clerigos/editar/${id}`,
  },
  ANNOUNCEMENTS: {
    HOME: '/programacao-e-eventos/banners',
    ADD: '/programacao-e-eventos/banners/adicionar',
    EDIT: (id: string) => `/programacao-e-eventos/banners/editar/${id}`,
    ALERT: '/programacao-e-eventos/alerta',
    EDIT_ALERT: '/programacao-e-eventos/alerta/editar',
  },
  CALENDAR: {
    HOME: '/programacao-e-eventos',
    ADD_EVENT: '/programacao-e-eventos/adicionar-evento',
    ADD_EVENT_WITH_DATE: (date: string) => `/programacao-e-eventos/adicionar-evento?date=${date}`,
    EDIT_EVENT: (id: string) => `/programacao-e-eventos/evento/${id}/editar`,
  },
  SECRETARIAT: {
    HOME: '/dados-institucionais/secretaria',
    EDIT: '/dados-institucionais/secretaria/editar',
    DONATIONS: '/dados-institucionais/secretaria/doacoes',
  },
  PASTORALS: '/dados-institucionais/pastorais',
  APPOINTMENTS: {
    HOME: '/agenda-pastoral',
    AGENDA: '/agenda-pastoral/agenda',
    MANAGE: '/agenda-pastoral/gerenciar',
    LIST: '/agenda-pastoral/solicitacoes',
    ADD: '/agenda-pastoral/adicionar',
    ADD_WITH_DATE: (date: string) => `/agenda-pastoral/adicionar?date=${date}`,
    EDIT: (id: string) => `/agenda-pastoral/editar/${id}`,
    REPORT: '/agenda-pastoral/relatorio',
    DETAILS: (id: string) => `/agenda-pastoral/${id}`,
    BLOCKS: '/agenda-pastoral/bloqueios',
  },
  PASTORAL_AGENTS: {
    HOME: '/agenda-pastoral/agentes-pastorais',
    ADD: '/agenda-pastoral/agentes-pastorais/adicionar',
    EDIT: (id: string) => `/agenda-pastoral/agentes-pastorais/editar/${id}`,
    SCHEDULE: (id: string) => `/agenda-pastoral/agentes-pastorais/${id}/horarios`,
    BLOCKED_DATES: (id: string) => `/agenda-pastoral/agentes-pastorais/${id}/bloqueios`,
  },
  APPOINTMENT_SERVICES: {
    HOME: '/agenda-pastoral/categorias-atendimento',
    ADD: '/agenda-pastoral/categorias-atendimento/adicionar',
    EDIT: (id: string) => `/agenda-pastoral/categorias-atendimento/editar/${id}`,
  },
  HELP: {
    HOME: '/ajuda',
    APPOINTMENTS: '/ajuda/atendimentos',
    SECRETARIAT: '/ajuda/secretaria',
    COMMUNITIES: '/ajuda/comunidades',
    CLERGY: '/ajuda/clerigos',
    ANNOUNCEMENTS: '/ajuda/avisos',
    USERS: '/ajuda/usuarios',
    FIRST_STEPS: '/ajuda/primeiros-passos',
    FAQ: '/ajuda/faq',
  },
} as const;
